name: CI/CD Pipeline (Local Self-Hosted)

on:
  push:
    branches:
      - main

jobs:
  cicd:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Clean previous build artifacts
        run: |
          sudo rm -rf build/
          sudo rm -rf src/main/resources/application.properties

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0

      - name: Generate application.properties
        run: |
          sudo mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_PROPERTIES }}" | sudo tee src/main/resources/application-prod.properties > /dev/null

      - name: Build with Gradle
        run: ./gradlew bootjar

      - name: Stop existing server
        run: |
          # 기존 서버 프로세스 종료
          sudo pkill -f "java.*matilda" || true
          sleep 3

      - name: Deploy to application directory
        run: |
          # lavatory 디렉토리가 없으면 생성
          sudo mkdir -p /home/lavatory
          
          # 기존 jar 파일들 백업 및 제거
          if [ -d "/home/lavatory/libs" ]; then
            sudo rm -rf /home/lavatory/libs.backup
            sudo mv /home/lavatory/libs /home/lavatory/libs.backup
          fi
          
          # 새 빌드 파일들 복사
          sudo cp -r build/libs /home/lavatory/
          
          # start-server.sh가 없으면 생성
          if [ ! -f "/home/lavatory/start-server.sh" ]; then
            echo '#!/bin/bash' | sudo tee /home/lavatory/start-server.sh > /dev/null
            echo 'cd /home/lavatory' | sudo tee -a /home/lavatory/start-server.sh > /dev/null
            echo 'java -Dspring.profiles.active=prod -jar libs/*.jar' | sudo tee -a /home/lavatory/start-server.sh > /dev/null
            sudo chmod +x /home/lavatory/start-server.sh
          fi

      - name: Start server
        run: |
          cd /home/lavatory
          ./start-server.sh &
          echo "Server starting in background..."

      - name: Cleanup
        if: always()
        run: |
          # 임시 파일 정리
          sudo rm -rf build/
          sudo rm -f src/main/resources/application.properties
